---
title: "Second_Attemp"
author: "Michelle Dai"
date: '2022-05-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(causaldata)
library(dbplyr)
library(ggdag)
library(tidyverse)
library(broom)
data <- read.csv(file="marketing_campaign.csv")
```

```{r}
data$TotalPurchase <- data$NumWebPurchases+ data$NumCatalogPurchases+data$NumStorePurchases
data_sub <- data %>% select(Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Recency, Complain, NumDealsPurchases, TotalPurchase, NumWebVisitsMonth)
```

```{r, message=FALSE, warning=FALSE}
library(visdat)
vis_dat(data_sub) #+ labs(title = "Missing Data For Sub Dataset")
```


```{r}
# impute missing data on alcoholhowmuch
library(mice)
library(MatchThem)
library(survey)
set.seed(1)

data_sub_imp <- mice(data_sub, 5, "pmm", printFlag = FALSE)

data_sub_complete <- complete(data_sub_imp)
```

```{r}
data_sub_complete <- data_sub_complete %>% 
  mutate(Education = ifelse(Education == "2n Cycle", 0, Education))%>% 
  mutate(Education = ifelse(Education == "Basic", 1, Education)) %>% 
  mutate(Education = ifelse(Education == "Graduation", 2, Education)) %>% 
  mutate(Education = ifelse(Education == "Master", 3, Education)) %>% 
  mutate(Education = ifelse(Education == "PhD", 4, Education)) %>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Single", 0, Marital_Status)) %>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Together", 1, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Married", 2, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Divorced", 3, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Widow", 4, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Alone", 5, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "Absurd", 6, Marital_Status))%>% 
  mutate(Marital_Status = ifelse(Marital_Status == "YOLO", 7, Marital_Status))
  
data_continuous <- data_sub_complete

data_sub_complete <- data_sub_complete %>% mutate(NumWebVisitsMonth = ifelse(NumWebVisitsMonth>=6, 1, 0))
```

```{r}
purchase <- dagify(
  NumWebVisitsMonth ~ Year_Birth + Education +Marital_Status+ Kidhome + Teenhome + Recency + NumDealsPurchases,
  TotalPurchase ~ Marital_Status + Income + Kidhome + Teenhome + Recency + Complain + NumDealsPurchases,
  exposure = "NumWebVisitsMonth",
  outcome = "TotalPurchase",
  labels = c(
    NumWebVisitsMonth = "#Web Visit Last Month",
    Year_Birth = "Birth Year",
    Education = "Education",
    Marital_Status = "Marital Status",
    Kidhome = "#Kids at Home",
    Teenhome = "#Teenagers at Home",
    Recency = "#Days since Last Purchase",
    NumDealsPurchases = "#Purchase using Discount",
    Income = "Income",
    TotalPurchase = "Total Purchase",
    Complain = "Complain"
  )
)
ggdag_status(purchase, use_labels = "label", text = FALSE) +
  guides(fill = "none", color = "none")

dagify(
  NumWebVisitsMonth ~ Year_Birth + Education +Marital_Status+ Kidhome + Teenhome + Recency + NumDealsPurchases,
  TotalPurchase ~ Marital_Status + Income + Kidhome + Teenhome + Recency + Complain + NumDealsPurchases,
  exposure = "NumWebVisitsMonth",
  outcome = "TotalPurchase",
  labels = c(
    NumWebVisitsMonth = "#Web Visit Last Month",
    Year_Birth = "Birth Year",
    Education = "Education",
    Marital_Status = "Marital Status",
    Kidhome = "#Kids at Home",
    Teenhome = "#Teenagers at Home",
    Recency = "#Days since Last Purchase",
    NumDealsPurchases = "#Purchase using Discount",
    Income = "Income",
    TotalPurchase = "Total Purchase",
    Complain = "Complain"
  )
) %>%
ggdag_adjustment_set(text_col = "black")
```


## Propensity Score Model

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(broom)
library(smd)
library(gtsummary)
library(survey)

data_sub_complete %>%
  tbl_summary(
    by = NumWebVisitsMonth, 
    include = c(
      "Year_Birth", "Education", "Marital_Status", "Kidhome", "Teenhome", "Recency", "NumDealsPurchases")) %>%
  add_overall()
```


```{r, results='hide', message=FALSE, warning=FALSE}
data_sub_complete <- 
  glm(NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases, 
    data = data_sub_complete,
    family = binomial()) %>%
  augment(type.predict = "response",
          data = data_sub_complete) # concatenation
data_sub_complete %>%
  select(NumWebVisitsMonth, .fitted)
```

```{r, message=FALSE, warning=FALSE}
ggplot(data_sub_complete, aes(x= .fitted, fill = as.factor(NumWebVisitsMonth))) + 
  geom_histogram(bins = 30) +geom_vline(xintercept = median(data_sub_complete[data_sub_complete$NumWebVisitsMonth == 0, ]$.fitted), linetype="twodash", 
                color = "red", size=1)+geom_vline(xintercept = median(data_sub_complete[data_sub_complete$NumWebVisitsMonth == 1, ]$.fitted), linetype="twodash", 
                color = "turquoise4", size=1)+
  labs(x="Propensity Score", y="Count", title= "Distribution of Propensity Score")

median(data_sub_complete[data_sub_complete$NumWebVisitsMonth == 0, ]$.fitted)
median(data_sub_complete[data_sub_complete$NumWebVisitsMonth == 1, ]$.fitted)
```


```{r, message=FALSE, warning=FALSE}
data_sub_complete_ato <- glm(NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases,
                         data=data_sub_complete, family = binomial()) %>%
  augment(data_sub_complete, type.predict = "response") %>%
  mutate(wt_ato = (1 - NumWebVisitsMonth)* .fitted + NumWebVisitsMonth * (1 - .fitted))
```


```{r, message=FALSE, warning=FALSE}
des <- svydesign(
  ids = ~1,
  data =  data_sub_complete_ato,
  weight = ~ wt_ato
)

des %>%
  tbl_svysummary(
    by = NumWebVisitsMonth, 
    include = c(
      "Year_Birth", "Education", "Marital_Status", "Kidhome", "Teenhome", "Recency", "NumDealsPurchases")) %>%
  add_overall()
```

```{r, message=FALSE, warning=FALSE}

#df_plot_ps <- data_sub_complete_ato %>% distinct() %>%
#  tidyr::pivot_wider(names_from = income,
#                     values_from = .fitted, 
#                     names_prefix = "income_p")

for_plot <- data_sub_complete_ato %>% distinct() %>%
  pivot_wider(names_from = NumWebVisitsMonth,
              values_from = .fitted,
              names_prefix = "NumWebVisitsMonth_p")
#for_plot <- as.data.frame(for_plot)
#for_plot$NumWebVisitsMonth_p1 <- unlist(for_plot$NumWebVisitsMonth_p1)
#for_plot$NumWebVisitsMonth_p0 <- unlist(for_plot$NumWebVisitsMonth_p0)
```


```{r, message=FALSE, warning=FALSE}
ggplot(for_plot) +
  geom_histogram(bins = 50,
                 aes(x = NumWebVisitsMonth_p1, 
                     weight = wt_ato),  
                 fill = "cornflower blue") +
  geom_histogram(bins = 50,
                 aes(x = NumWebVisitsMonth_p0,
                     weight = wt_ato,
                     y = - stat(count)),
                 fill = "orange") + 
  scale_y_continuous("Count", label = abs) + 
  scale_x_continuous("Propensity Score (ATO Weighted)") +
  geom_label(
    label = "Visit >= 7", 
    x = 0.1,
    y = 10,
  )+
    geom_label(
    label = "Visit < 7", 
    x = 0.1,
    y = -10,
  )+ labs(title= "Distribution of Propensity Score (ATO Weighted)")
```

```{r, message=FALSE, warning=FALSE}
ecdf_1 <- data_sub_complete_ato %>%
  filter(NumWebVisitsMonth == 1) %>%
  arrange(Income) %>%
  mutate(cum_pct_ato = cumsum(wt_ato) / sum(wt_ato))

ecdf_0 <- data_sub_complete_ato %>%
  filter(NumWebVisitsMonth == 0) %>%
  arrange(Income) %>%
  mutate(cum_pct_ato = cumsum(wt_ato) / sum(wt_ato))
```

```{r, message=FALSE, warning=FALSE}
ggplot(ecdf_1, aes(x = Income, y = cum_pct_ato, color = "Yes")) +
  geom_line() +
  geom_line(data = ecdf_0, 
            aes(x = Income, y = cum_pct_ato, color = "No")) + labs(x = "Income after ATO weighting", y = "(ATO Weighted) Percent <= x", title="ATO Weighted ECDF for Income", color = "NumWebVisitsMonth")
```

```{r, message=FALSE, warning=FALSE}
ggplot(ecdf_1, aes(x = Year_Birth, y = cum_pct_ato, color = "Yes")) +
  geom_line() +
  geom_line(data = ecdf_0, 
            aes(x = Income, y = cum_pct_ato, color = "No")) + labs(x = "Year_Birth after ATO weighting", y = "(ATO Weighted) Percent <= x", title="ATO Weighted ECDF for Year_Birth", color = "NumWebVisitsMonth")
```


```{r, message=FALSE, warning=FALSE}
ggplot(ecdf_1, aes(x = Recency, y = cum_pct_ato, color = "Yes")) +
  geom_line() +
  geom_line(data = ecdf_0, 
            aes(x = Recency, y = cum_pct_ato, color = "No")) + labs(x = "Recency after ATO weighting", y = "(ATO Weighted) Percent <= x", title="ATO Weighted ECDF for Recency", color = "NumWebVisitsMonth")
```


```{r, message=FALSE, warning=FALSE}
library(rsample)
library(PSW)
#fit inverse probablity weight model
fit_ipw <- function(split, ...) {
  .df <- analysis(split)
  # fit propensity score model
  propensity_model <- glm(
    NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases,
    data = .df,
    family = binomial()
  )
  # calculate inverse probability weights
  .df <- propensity_model %>% 
    augment(type.predict = "response", data = .df) %>% 
    mutate(wt_ato = (1 - NumWebVisitsMonth)* .fitted + NumWebVisitsMonth * (1 - .fitted))
  # fit correctly bootsrapped ipw model
  # outcome model 
  lm(TotalPurchase ~ NumWebVisitsMonth, data = .df, weights = wt_ato) %>% 
    tidy()
}

# fit ipw model to bootstrapped samples
ipw_results <- bootstraps(data_sub_complete_ato, 1000, apparent = TRUE) %>% 
  mutate(results = map(splits, fit_ipw))
```

```{r, message=FALSE, warning=FALSE}
# get t-statistic-based CIs
boot_estimate <- int_t(ipw_results, results) %>%
  filter(term == c("(Intercept)", "NumWebVisitsMonth"))
boot_estimate
```

```{r, message=FALSE, warning=FALSE}
library(rsample)
library(PSW)
#fit inverse probablity weight model
fit_ipw <- function(split, ...) {
  .df <- analysis(split)
  # fit propensity score model
  propensity_model <- glm(
    NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases,
    data = .df,
    family = binomial()
  )
  # calculate inverse probability weights
  .df <- propensity_model %>% 
    augment(type.predict = "response", data = .df)
  # outcome model 
  lm(TotalPurchase ~ NumWebVisitsMonth, data = .df) %>% 
    tidy()
}

# fit ipw model to bootstrapped samples
ipw_results <- bootstraps(data_sub_complete_ato, 1000, apparent = TRUE) %>% 
  mutate(results = map(splits, fit_ipw))
```


```{r, message=FALSE, warning=FALSE}
# get t-statistic-based CIs
boot_estimate <- int_t(ipw_results, results) %>%
  filter(term == c("(Intercept)", "NumWebVisitsMonth"))
boot_estimate
```

# Continuous Exposure

inverse propensity weights (IPW)

```{r}
# the numerator
mod_num <- lm(NumWebVisitsMonth ~ 1, data = data_continuous)

num <- dnorm(x = data_continuous$NumWebVisitsMonth, # treatment 
             mean = fitted.values(mod_num), # fitted values
             sd = summary(mod_num)$sigma) # model sigma

mod_den <- lm(NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases, data = data_continuous)

den <- dnorm(x = data_continuous$NumWebVisitsMonth, # treatment variable
             mean = fitted.values(mod_den), # fitted values
             sd = summary(mod_den)$sigma)

data_continuous <- data_continuous %>%
  mutate(ipw_s = num/den)

summary(data_continuous$ipw_s)
```


```{r}
ggplot(data_continuous, aes(ipw_s)) +
  geom_density(col = "#E69F00", fill = "#E69F0095") + 
  scale_x_log10() + 
  theme_minimal(base_size = 20) + 
  xlab("Stabilized Weights")
```

```{r, message=FALSE, warning=FALSE}
library(rsample)
library(PSW)
#fit inverse probablity weight model
fit_ipw <- function(split, ...) {
  .df <- analysis(split)
  # fit propensity score model
  mod_num <- lm(NumWebVisitsMonth ~ 1, data = .df)
  num <- dnorm(x = .df$NumWebVisitsMonth, # treatment 
             mean = fitted.values(mod_num), # fitted values
             sd = summary(mod_num)$sigma) # model sigma
  mod_den <- lm(NumWebVisitsMonth ~ Year_Birth + as.factor(Education) +as.factor(Marital_Status)+ Kidhome + Teenhome + Recency + NumDealsPurchases, data = .df)
  den <- dnorm(x = .df$NumWebVisitsMonth, # treatment variable
             mean = fitted.values(mod_den), # fitted values
             sd = summary(mod_den)$sigma)

  .df <- .df %>%
    mutate(ipw_s = num/den)

  # fit correctly bootsrapped ipw model
  # outcome model 
  lm(TotalPurchase ~ NumWebVisitsMonth, data = .df) %>% 
    tidy()
}

# fit ipw model to bootstrapped samples
ipw_results <- bootstraps(data_continuous, 1000, apparent = TRUE) %>% 
  mutate(results = map(splits, fit_ipw))
```


```{r, message=FALSE, warning=FALSE}
# get t-statistic-based CIs
boot_estimate <- int_t(ipw_results, results) %>%
  filter(term == c("(Intercept)", "NumWebVisitsMonth"))
boot_estimate
```




